defaults: &defaults  
  host: localhost  
  port: 6379  
  password: 
development:  
  <<: *defaults
  host: localhost
test:  
  <<: *defaults

staging:  
  <<: *defaults

production: &production
  <<: *defaults
