
:pidfile: ./tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log
:queues:
  - [default, 1]
  - [send_mail, 10]
staging: 
  :concurrency: 5

development: 
  :concurrency: 5

production: 
  :concurrency: 50